name: Playwright Tests

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Choose environment'
        required: true
        default: 'qa'
        type: choice
        options:
          - qa
      browser:
        description: 'Choose browser'
        required: true
        default: 'chromium'
        type: choice
        options:
          - all
          - chromium
          - firefox
          - webkit

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      ENV: ${{ github.event.inputs.env }}
      QA_BASE_URL: https://club-administration.qa.qubika.com

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: |
          if [ "${{ github.event.inputs.browser }}" = "firefox" ]; then
            npx playwright install firefox
          elif [ "${{ github.event.inputs.browser }}" = "chromium" ]; then
            npx playwright install chromium
          else
            npx playwright install --with-deps
          fi

      - name: Run Playwright tests
        run: |
          if [ "${{ github.event.inputs.browser }}" = "all" ]; then
            npx playwright test
          else
            npx playwright test --project=${{ github.event.inputs.browser }}
          fi

      - name: Upload Playwright HTML report as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report

      - name: Deploy Playwright report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: playwright-report
          publish_branch: gh-pages
          force_orphan: true

      - name: Print report URL
        if: always()
        run: |
          REPO_FULL="${{ github.repository }}"
          OWNER="${{ github.repository_owner }}"
          REPO_NAME="${REPO_FULL#*/}"
          echo "Playwright report published at: https://${OWNER}.github.io/${REPO_NAME}/"
